# Site settings
title: GhettoBox
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: "http://powerfulwizard.net/ghetto-box-live-site"
url: "http://powerfulwizard.net/ghetto-box-live-site"

include: [".nojekyll"]

# Build settings
markdown: kramdown
kramdown:
  use_coderay: true
  coderay:
    coderay_tab_width: 4
    coderay_css: style
    coderay_line_numbers: nil

permalink: pretty
